# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
require_relative '../mobile_sdk/SalesforceMobileSDK-iOS/mobilesdk_pods'

platform :ios, '17.0'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

project 'NiwasLos.xcodeproj'
target 'NiwasLos' do
  source 'https://cdn.cocoapods.org/'
  $config = use_native_modules!

  use_react_native!(
    :path => $config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  use_mobile_sdk!(:path => '../mobile_sdk/SalesforceMobileSDK-iOS')
  pod 'SalesforceReact', :path => '../node_modules/react-native-force'
end

pre_install do |installer|
  # Mobile SDK pre install
  mobile_sdk_pre_install(installer)
end
 
post_install do |installer|
  # Salesforce Mobile SDK signposts
  signposts_post_install(installer)

  # React Native post install
  if defined?($config) && $config[:reactNativePath]
    react_native_post_install(
      installer,
      $config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  else
    react_native_post_install(
      installer,
      :mac_catalyst_enabled => false
    )
  end

  # Salesforce Mobile SDK post install
  mobile_sdk_post_install(installer)
end
